@startuml

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response

Alice -> Bob: Authentication Request 2

Alice -> Bob: Authentication Request 3

@enduml
