@startuml

hide footbox
skinparam sequenceMessageAlign center

participant system1 as s1 #E1D5E7
participant system2 as s2 #E1D5E7
|||

activate s1 #F5F5F5
s1 -> s2: Payment data request
activate s2 #F5F5F5
|||

s2 -> s2: Verification
activate s2 #DFDFDF
deactivate s2

s1 <-- s2: Payment data
|||

alt #FFF5F5 Error
s1 <-- s2: Payment wasn't found
deactivate s2
|||
end

deactivate s1
|||

s1 <-- s2: Payment wasn't found

s1 <-- s2: Payment wasn't found

@enduml
